import { Organisation, Section, Village, Producteur, Parcelle, Operation } from "@/types/organisation";

export const SEED_ORGANISATIONS: Organisation[] = [
  {
    id: "org-1",
    code: "ORG-001",
    nom: "SCOOP-CA Divo",
    type: "Coopérative",
    region: "Lôh-Djiboua",
    departement: "Divo",
    sous_prefecture: "Divo",
    localite: "Divo",
    president_nom: "Kouassi Michel",
    president_contact: ["0707070707"],
    date_creation: new Date("2020-01-15"),
    date_modification: new Date("2023-10-10"),
    statut: "actif"
  }
];

export const SEED_SECTIONS: Section[] = [
  {
    id: "sec-1",
    code: "SEC-001",
    id_organisation: "org-1",
    localite: "Section Nord",
    nom: "Section Nord",
    telephone: "0102030405",
    nb_producteurs: 150,
    tonnage_c_precedente: 1200,
    tonnage_c_cours: 800,
    tonnage_potentiel: 1500,
    president_nom: "Konan Yves",
    president_contact: ["0505050505"],
    secretaire_nom: "Kouame Anne",
    secretaire_contact: ["0606060606"],
    magasinier_nom: "Yao Paul",
    magasinier_contact: ["0404040404"],
    peseur_nom: "Brou Marc",
    peseur_contact: ["0303030303"],
    has_analyseur: true,
    vehicule_camionnette_nombre: 2,
    vehicule_camionnette_proprietaire: true,
    vehicule_liaison_nombre: 5,
    vehicule_liaison_proprietaire: true,
    vehicule_tricycle_nombre: 3,
    vehicule_tricycle_proprietaire: true,
    vehicule_moto_nombre: 10,
    vehicule_moto_proprietaire: false,
    materiel_dickey_john: true,
    materiel_kpm: true,
    materiel_couteaux: true,
    materiel_tableau: true,
    materiel_sondes: true,
    materiel_bascule: true,
    comm_coop: true,
    comm_pisteur: false,
    comm_autre_coop: false,
    comm_autre_acheteur: false,
    date_creation: new Date("2020-02-01"),
    date_creation_section: new Date("2020-02-01"),
    date_modification: new Date("2023-11-05"),
    statut: "actif"
  }
];

export const SEED_VILLAGES: Village[] = [
  {
    id: "vil-1",
    code: "VIL-001",
    type: "Village",
    id_organisation: "org-1",
    id_section: "sec-1",
    localite: "Divo",
    nom: "Village Centre",
    chef_nom: "N'Guessan Pierre",
    chef_contact: ["0101010101"],
    nombre_habitants: 1200,
    nombre_hommes: 600,
    nombre_femmes: 600,
    nombre_enfants_scolarises: 300,
    eau_courante: true,
    pompe_hydraulique: true,
    puits: false,
    riviere_marigot: false,
    electricite_reseau: true,
    electricite_solaire: false,
    electricite_lampes: false,
    dispensaire: true,
    pharmacie: true,
    ecole_primaire: true,
    college_lycee: true,
    culture_cacao: true,
    culture_cafe: true,
    culture_riz: false,
    culture_mais: true,
    culture_hevea: false,
    culture_palmier: false,
    culture_maraicheres: true,
    elevage_ovin: true,
    elevage_bovin: false,
    elevage_porcin: false,
    elevage_autre: false,
    commerces: true,
    artisanat: true,
    om_orange: true,
    momo_mtn: true,
    flooz_moov: false,
    autres_paiement: false,
    date_creation: new Date("2020-02-10"),
    date_modification: new Date("2023-11-20"),
    statut: "actif"
  }
];

export const SEED_PRODUCTEURS: Producteur[] = [
  {
    id: "prod-1",
    code: "ORG-001-SEC-001-VIL-001-001",
    id_organisation: "org-1",
    id_section: "sec-1",
    id_village: "vil-1",
    nom_complet: "KOUASSI JEAN",
    date_naissance: new Date("1980-05-15"),
    lieu_naissance: "DIVO",
    nb_femmes: 1,
    nb_enfants: 4,
    nb_filles: 2,
    nb_garcons: 2,
    nb_moins_5_ans: 1,
    nb_enfants_scolarises: 3,
    scolarises_primaire_filles: 1,
    scolarises_primaire_garcons: 1,
    scolarises_secondaire_filles: 0,
    scolarises_secondaire_garcons: 1,
    scolarises_superieur_filles: 0,
    scolarises_superieur_garcons: 0,
    eau_courante: true,
    pompe_hydraulique: false,
    puits: true,
    riviere_marigot: false,
    electricite_reseau: true,
    electricite_solaire: false,
    electricite_lampe: false,
    electricite_aucun: false,
    materiaux_mur: "Briques/Ciment",
    toiture: "Tôle",
    soins_plantes_tradi: "Souvent",
    soins_dispensaire: "Toujours",
    interet_compte_bancaire: true,
    interet_epargne: true,
    usage_mobile_money: "Toujours",
    usage_virement: "Jamais",
    usage_especes: "Souvent",
    usage_tontine: "Peu",
    credit_intrants: true,
    credit_soudure: false,
    pret_scolaire: true,
    credit_acces_intrants: true,
    credit_biens_conso: false,
    credit_assurance_maladie: true,
    credit_assurance_agricole: true,
    credit_assurance_retraite: false,
    credit_conseil_agricole: true,
    credit_rehabilitation: false,
    cacao_nb_plantations: 2,
    cacao_superficie: 5.5,
    cacao_production: 4.2,
    hevea: false,
    palmier: false,
    cafe: true, cafe_nb_plantations: 1, cafe_superficie: 1.0, cafe_production: 0.5,
    mais: true, mais_nb_plantations: 1, mais_superficie: 0.5, mais_production: 0.2,
    riz: false,
    maraichere: true, maraichere_nb_plantations: 1, maraichere_superficie: 0.1, maraichere_production: 0.1,
    date_creation: new Date("2024-01-10"),
    date_modification: new Date("2024-01-10"),
    statut: "actif"
  },
  {
    id: "prod-2",
    code: "ORG-001-SEC-001-VIL-001-002",
    id_organisation: "org-1",
    id_section: "sec-1",
    id_village: "vil-1",
    nom_complet: "KONÉ MARIE",
    date_naissance: new Date("1985-08-22"),
    lieu_naissance: "LAKOTA",
    nb_femmes: 0,
    nb_enfants: 2,
    nb_filles: 2,
    nb_garcons: 0,
    nb_moins_5_ans: 0,
    nb_enfants_scolarises: 2,
    scolarises_primaire_filles: 2,
    scolarises_primaire_garcons: 0,
    scolarises_secondaire_filles: 0,
    scolarises_secondaire_garcons: 0,
    scolarises_superieur_filles: 0,
    scolarises_superieur_garcons: 0,
    eau_courante: false,
    pompe_hydraulique: true,
    puits: false,
    riviere_marigot: false,
    electricite_reseau: true,
    electricite_solaire: true,
    electricite_lampe: false,
    electricite_aucun: false,
    materiaux_mur: "Terre battue séchée",
    toiture: "Tôle",
    soins_plantes_tradi: "Toujours",
    soins_dispensaire: "Souvent",
    interet_compte_bancaire: false,
    interet_epargne: true,
    usage_mobile_money: "Souvent",
    usage_virement: "Jamais",
    usage_especes: "Toujours",
    usage_tontine: "Souvent",
    credit_intrants: false,
    credit_soudure: true,
    pret_scolaire: false,
    credit_acces_intrants: false,
    credit_biens_conso: true,
    credit_assurance_maladie: false,
    credit_assurance_agricole: false,
    credit_assurance_retraite: false,
    credit_conseil_agricole: false,
    credit_rehabilitation: false,
    cacao_nb_plantations: 1,
    cacao_superficie: 2.5,
    cacao_production: 1.8,
    hevea: false,
    palmier: false,
    cafe: false,
    mais: true,
    riz: false,
    maraichere: true,
    date_creation: new Date("2024-02-15"),
    date_modification: new Date("2024-02-15"),
    statut: "actif"
  }
];

export const SEED_PARCELLES: Parcelle[] = [
  {
    id: "parc-1",
    code: "P-089",
    id_producteur: "prod-1",
    id_organisation: "org-1",
    age_plantation: 12,
    superficie_declaree: 3.5,
    superficie_reelle: 3.42,
    production_declaree: 2.5,
    latitude: 5.84,
    longitude: -5.36,
    maladie_pourriture_brune: "Peu",
    maladie_swollen_shoot: "Inexistant",
    maladie_parasites: "Peu",
    maladie_autre: "Inexistant",
    engrais: "Peu",
    pesticides: "Peu",
    insecticides: "Peu",
    fongicides: "Peu",
    herbicides: "Moyen",
    conseil_anader: true,
    conseil_partenaires: false,
    conseil_prives: false,
    conseil_frequence: "01 fois trimestre",
    conseil_interet: true,
    sechage_claie_hauteur: true,
    sechage_claie_sol: false,
    sechage_plastique_sol: false,
    sechage_ciment: false,
    equipement_machettes: true,
    equipement_gourdins: true,
    equipement_limes: true,
    equipement_houe: false,
    equipement_secateur: true,
    equipement_combinaison: true,
    equipement_gants: true,
    equipement_lunettes: false,
    equipement_masque: false,
    equipement_bottes: true,
    comm_coop: true,
    comm_pisteur: false,
    comm_autre_coop: false,
    comm_autre_acheteur: false,
    date_creation: new Date("2020-05-10"),
    date_modification: new Date("2023-11-15"),
    statut: "active"
  },
  {
    id: "parc-2",
    code: "P-090",
    id_producteur: "prod-1",
    id_organisation: "org-1",
    age_plantation: 5,
    superficie_declaree: 2.0,
    superficie_reelle: 2.08,
    production_declaree: 1.7,
    latitude: 5.85,
    longitude: -5.35,
    maladie_pourriture_brune: "Inexistant",
    maladie_swollen_shoot: "Inexistant",
    maladie_parasites: "Peu",
    maladie_autre: "Inexistant",
    engrais: "A dose recommandée",
    pesticides: "Peu",
    insecticides: "Peu",
    fongicides: "Peu",
    herbicides: "Peu",
    conseil_anader: true,
    conseil_partenaires: true,
    conseil_prives: false,
    conseil_frequence: "01 par mois",
    conseil_interet: true,
    sechage_claie_hauteur: true,
    sechage_claie_sol: false,
    sechage_plastique_sol: false,
    sechage_ciment: false,
    equipement_machettes: true,
    equipement_gourdins: true,
    equipement_limes: true,
    equipement_houe: false,
    equipement_secateur: true,
    equipement_combinaison: true,
    equipement_gants: true,
    equipement_lunettes: true,
    equipement_masque: true,
    equipement_bottes: true,
    comm_coop: true,
    comm_pisteur: false,
    comm_autre_coop: false,
    comm_autre_acheteur: false,
    date_creation: new Date("2021-06-20"),
    date_modification: new Date("2023-11-15"),
    statut: "active"
  }
];

export const SEED_OPERATIONS: Operation[] = [
  {
    id: "op-1",
    id_village: "vil-1",
    id_producteur: "prod-1",
    axe_collecte: "Route Principale",
    id_parcelle: "parc-1",
    date_recolte_1: new Date("2024-10-01"),
    date_ecabossage: new Date("2024-10-05"),
    ecabossage_debut: "08:00",
    ecabossage_fin: "14:00",
    ecabossage_duree: "6h",
    cout_ecabossage: 5000,
    outils_machette: true,
    outils_gourdin: true,
    outils_couteau: false,
    date_transport: new Date("2024-10-05"),
    fermentation_debut: new Date("2024-10-06"),
    fermentation_fin: new Date("2024-10-12"),
    materiel_feuilles: true,
    materiel_caisses: false,
    sechage_debut: new Date("2024-10-13"),
    sechage_fin: new Date("2024-10-20"),
    aire_claie_bambou: true,
    aire_plastique_sol: false,
    aire_plastique_ciment: false,
    aire_cimentee: false,
    ensachage_debut: new Date("2024-10-21"),
    ensachage_fin: new Date("2024-10-21"),
    nb_sacs_brousse: 15,
    poids_estimatif: 1200,
    lieu_stockage_etat: "Bon",
    date_livraison: new Date("2024-10-22"),
    manutention_dechargement: true,
    manutention_sonde: true,
    manutention_pesee: 1180,
    manutention_analyse: true,
    validation_statut: "Accepté",
    paiement_especes: false,
    paiement_cheque: true,
    montant_cheque: 1180000, // 1000 FCFA/kg
    numero_cheque: "CHQ-998877",
    banque: "NSIA",
    retenue_mec: true,
    retenue_mec_taux: 10000,
    retenue_epargne: true,
    retenue_epargne_taux: 5000,
    date_creation: new Date("2024-10-22"),
    statut: "Payé"
  }
];
